# Site settings
title: "Whole Beast Rag | Fertilize Your Brain"
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Whole Beast Rag operated from January 2012 to November 2013. The idea will live on.
  We dabble in literature, interviews, supplements, translations and other transmissions.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "localhost:4000" # the base hostname & protocol for your site
permalink: /articles/:title
twitter_username: perry_keisha
github_username:  keishaperry

# Build settings
markdown: kramdown

#gems: ['jekyll-lunr-js-search']